version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: networking_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: networking_db
      POSTGRES_USER: networking
      POSTGRES_PASSWORD: networking
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: